INSERT INTO product_entity (
    id,
    name,
    image,
    category,
    measure_type,
    measure_count,
    unit_of_measure,
    shelf_life_count,
    shelf_life_unit,
    price,
    stock_at_this_price,
    rating,
    dietary_icons,
                            stock_count
) VALUES (
    1,
    'Rye Bread',
    'https://tse1.mm.bing.net/th/id/OIP.Q1haw2yz-ByTjxq8yNUaDAHaGd?pid=Api',
  'bakery/bread/rye_bread',
  'weight',
500,
     'gram',
3,
'days',
4.40,
4,
          4,
'{"suitable-for-freezing", "vegan"}',
          4
         );
INSERT INTO product_entity (
    id,
    name,
    image,
    category,
    measure_type,
    measure_count,
    unit_of_measure,
    shelf_life_count,
    shelf_life_unit,
    price,
    stock_at_this_price,
    rating,
    dietary_icons,
    stock_count
) VALUES (
             2,
             'Paris Baguette',
             'https://tse4.mm.bing.net/th/id/OIP.KY9XzFZZJuZ4mNh5punCYwHaE7?r=0&pid=Api',
             'bakery/baguettes',
             'weight',
             200,
             'gram',
             3,
             'days',
             2.50,
             2,
             4.5,
             '{"suitable-for-freezing"}',
             2
         );

INSERT INTO product_entity (
    id,
    name,
    image,
    category,
    measure_type,
    measure_count,
    unit_of_measure,
    shelf_life_count,
    shelf_life_unit,
    price,
    stock_at_this_price,
    rating,
    dietary_icons,
    stock_count
) VALUES (
             3,
             'White Bread',
             'https://tse2.mm.bing.net/th/id/OIP.wydu4o66PZtc6xgdyVLK3AHaLH?r=0&pid=Api',
             'bakery/bread/white_bread',
             'weight',
             600,
             'gram',
             3,
             'days',
             3.50,
             5,
             4.5,
             '{"suitable-for-freezing"}',
             5
         );